<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("On-line заявка");
?><?$APPLICATION->IncludeComponent("api:main.feedback", ".default", array(
	"IBLOCK_TYPE" => "altasib_feedback",
	"IBLOCK_ID" => "3",
	"INSTALL_IBLOCK" => "N",
	"REPLACE_FIELD_FROM" => "Y",
	"UNIQUE_FORM_ID" => "5460938835a46",
	"OK_TEXT" => "Спасибо, ваше обращение #TICKET_ID# принято.",
	"EMAIL_TO" => "dumkaaa72@gmail.com",
	"DISPLAY_FIELDS" => array(
		0 => "AUTHOR_NAME",
		1 => "AUTHOR_EMAIL",
		2 => "AUTHOR_PERSONAL_MOBILE",
		3 => "AUTHOR_WORK_COMPANY",
		4 => "AUTHOR_MESSAGE",
	),
	"REQUIRED_FIELDS" => array(
		0 => "AUTHOR_NAME",
		1 => "AUTHOR_EMAIL",
	),
	"CUSTOM_FIELDS" => array(
	),
	"ADMIN_EVENT_MESSAGE_ID" => array(
		0 => "7",
	),
	"USER_EVENT_MESSAGE_ID" => array(
		0 => "7",
	),
	"HIDE_FIELD_NAME" => "N",
	"TITLE_DISPLAY" => "N",
	"FORM_TITLE" => "",
	"FORM_TITLE_LEVEL" => "1",
	"FORM_STYLE_TITLE" => "",
	"FORM_STYLE" => "text-align:left;",
	"FORM_STYLE_DIV" => "overflow:hidden;padding:5px;",
	"FORM_STYLE_LABEL" => "display: block;min-width:175px;margin-bottom: 3px;float:left;",
	"FORM_STYLE_TEXTAREA" => "padding:3px 5px;min-width:380px;min-height:150px;",
	"FORM_STYLE_INPUT" => "min-width:220px;padding:3px 5px;",
	"FORM_STYLE_SELECT" => "min-width:232px;padding:3px 5px;",
	"FORM_STYLE_SUBMIT" => "",
	"FORM_SUBMIT_CLASS" => "",
	"FORM_SUBMIT_ID" => "",
	"FORM_SUBMIT_VALUE" => "Отправить",
	"USE_CAPTCHA" => "Y",
	"USE_HIDDEN_PROTECTION" => "N",
	"USE_PHP_ANTISPAM" => "N",
	"PHP_ANTISPAM_LEVEL" => "1",
	"INCLUDE_JQUERY" => "Y",
	"VALIDTE_REQUIRED_FIELDS" => "Y",
	"INCLUDE_PLACEHOLDER" => "Y",
	"INCLUDE_PRETTY_COMMENTS" => "N",
	"INCLUDE_FORM_STYLER" => "N",
	"HIDE_FORM_AFTER_SEND" => "Y",
	"SCROLL_TO_FORM_IF_MESSAGES" => "N",
	"SCROLL_TO_FORM_SPEED" => "1000",
	"BRANCH_ACTIVE" => "N",
	"SHOW_FILES" => "N",
	"UUID_LENGTH" => "10",
	"UUID_PREFIX" => "",
	"USER_AUTHOR_FIO" => "",
	"USER_AUTHOR_NAME" => "",
	"USER_AUTHOR_LAST_NAME" => "",
	"USER_AUTHOR_SECOND_NAME" => "",
	"USER_AUTHOR_EMAIL" => "",
	"USER_AUTHOR_PERSONAL_MOBILE" => "Телефон",
	"USER_AUTHOR_WORK_COMPANY" => "",
	"USER_AUTHOR_POSITION" => "",
	"USER_AUTHOR_PROFESSION" => "",
	"USER_AUTHOR_STATE" => "",
	"USER_AUTHOR_CITY" => "",
	"USER_AUTHOR_WORK_CITY" => "",
	"USER_AUTHOR_STREET" => "",
	"USER_AUTHOR_ADRESS" => "",
	"USER_AUTHOR_PERSONAL_PHONE" => "",
	"USER_AUTHOR_WORK_PHONE" => "",
	"USER_AUTHOR_FAX" => "",
	"USER_AUTHOR_MAILBOX" => "",
	"USER_AUTHOR_WORK_MAILBOX" => "",
	"USER_AUTHOR_SKYPE" => "",
	"USER_AUTHOR_ICQ" => "",
	"USER_AUTHOR_WWW" => "",
	"USER_AUTHOR_WORK_WWW" => "",
	"USER_AUTHOR_MESSAGE_THEME" => "",
	"USER_AUTHOR_MESSAGE" => "",
	"USER_AUTHOR_NOTES" => "",
	"AJAX_MODE" => "Y",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "Y",
	"SHOW_CSS_MODAL_AFTER_SEND" => "N",
	"CSS_MODAL_HEADER" => "Информация",
	"CSS_MODAL_FOOTER" => "",
	"CSS_MODAL_CONTENT" => "",
	"AJAX_OPTION_ADDITIONAL" => ""
	),
	false
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>